name: Secure Pipeline Demo - Java

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 (LTS)
      uses: actions/setup-java@v1
      with:
        java-version: 11
        architecture: x64
    - name: Restore Maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: java --version && mvn --version
    - name: Build project with Maven
      run: mvn -B clean package
    - name: Publish Artefact
      uses: actions/upload-artifact@v1
      with:
        name: Application Jar
        path: target/demo-0.0.1-SNAPSHOT.jar
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: rmkanda/gh-actions-secure-pipeline-java-demo/spring-sample-app
        tag_with_ref: true
  oss-scan:
    name: OSS Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven-3-jdk-11@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
  sast:
    name: Static Code Analysis with FindSecBugs
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 11 (LTS)
      uses: actions/setup-java@v1
      with:
        java-version: 11
        architecture: x64
    - name: Restore Maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run Spot Bugs
      continue-on-error: true
      run: mvn compile spotbugs:check
    - uses: jwgmeligmeyling/spotbugs-github-action@master
      with:
        path: '**/spotbugsXml.xml'
  container:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Build the Container image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - uses: anchore/scan-action@v2
      id: scan
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}